import common, pandas as pd, numpy as np
pd.set_option('display.width',250); pd.set_option('display.max_columns',60); pd.set_option('display.max_rows',300)
d = common.load()
print("=== rank_key(商品)別 ===")
g=d.groupby(d['rank_key'].fillna('NONE')).agg(n=('paid','size'),paid=('paid','sum'),mean=('paid','mean'),
   med=('paid','median'),sold_rate=('nsold',lambda s:(s>0).mean()), hit=('hit','mean'))
g['share']=g['paid']/d['paid'].sum()
print(g.sort_values('paid',ascending=False).round(3).to_string())
print("\n=== origin別 ===")
print(d.groupby(d['origin'].fillna('NONE')).agg(n=('paid','size'),paid=('paid','sum'),mean=('paid','mean')).round(2))
print("\n=== is_confident ===")
print(d.groupby(d['is_confident'].fillna('NONE')).agg(n=('paid','size'),paid=('paid','sum'),mean=('paid','mean'),sold_rate=('nsold',lambda s:(s>0).mean())).round(3))
print("\n=== type_label ===")
print(d.groupby(d['type_label'].fillna('NONE')).agg(n=('paid','size'),paid=('paid','sum'),mean=('paid','mean')).round(2))
print("\n=== n_legs(点数) ===")
print(d.groupby(d['n_legs'].fillna(-1)).agg(n=('paid','size'),mean=('paid','mean')).round(2))
print("\n=== pred_mean_payout 五分位 ===")
m=d['pred_mean_payout'].notna()
d.loc[m,'pq']=pd.qcut(d.loc[m,'pred_mean_payout'],5,labels=False)
print(d[m].groupby('pq').agg(n=('paid','size'),mean=('paid','mean'),pmp=('pred_mean_payout','median')).round(2))
print("\n=== 公開時刻→発走 リードタイム(分) ===")
d['pub']=pd.to_datetime(d['published_at'],errors='coerce')
d['start']=pd.to_datetime(d['start_at'].astype('Int64'),unit='s',errors='coerce')
d['lead_min']=(d['start']-d['pub']).dt.total_seconds()/60
sel=d[d['lead_min'].between(-60,2000)]
print("n with lead:",len(sel))
print(sel['lead_min'].describe().round(1))
sel=sel.copy(); sel['lq']=pd.qcut(sel['lead_min'],5,labels=False)
print(sel.groupby('lq').agg(n=('paid','size'),lead=('lead_min','median'),mean=('paid','mean'),sold_rate=('nsold',lambda s:(s>0).mean())).round(2))
print("\n=== avg_sold_minutes(買われた平均タイミング: 締切までの残り分) ===")
print(d['avg_sold_minutes'].describe().round(1))
